spring.application.name=data

spring.datasource.url=jdbc:sqlite:./data-db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# options: none | validate | update | create | create-drop
spring.jpa.hibernate.ddl-auto=create-drop

# show for easier debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true